version: '3.7'

networks:
  private:
    internal: true
    driver: bridge
  public:
    driver: bridge

services:

    # base:
    #   build:
    #     context: ./base
    #   ports:
    #     - "2222:22"

    nginx:
      build:
        context: ./nginx
      volumes:
        - ~/www/:/var/www:delegated
        - ../web-data/logs/nginx/:/var/log/nginx
        - ./nginx/inc/:/etc/nginx/inc
        - ./nginx/sites-available/:/etc/nginx/sites-available
        - ./nginx/ssl/:/etc/nginx/ssl
      ports:
        - "80:7280"
        - "443:7243"
        - "7480:7480"
        - "7443:7443"
      networks:
        - public
        - private
      depends_on:
        - php-fpm7.2
        - php-fpm7.4

    php-fpm7.2:
      build:
        context: ./php-fpm7.2
      volumes:
        - ./base/my.bashrc:/root/.bashrc
        - ~/www/:/var/www:delegated
        - ../web-data/composer/:/.composer:delegated
      # expose:
      #   - "9072"
      #   - "9972"
      networks:
        - private
        - public

    php-fpm7.4:
      build:
        context: ./php-fpm7.4
      volumes:
        - ./base/my.bashrc:/root/.bashrc
        - ~/www/:/var/www:delegated
        - ../web-data/composer/:/.composer:delegated
      # expose:
      #   - "9074"
      #   - "9974"
      networks:
        - private
        - public

    mysql5.7:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_USER: root
        MYSQL_PASSWORD: 1234
      volumes:
        - ../web-data/mysql5.7/:/var/lib/mysql
        - ./mysql5.7/:/etc/mysql/conf.d
        - ./mysql5.7/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
      ports:
        - "23306:3306"
      networks:
        - private
        - public

    mysql8.0:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_PASSWORD: 1234
      volumes:
        - ../web-data/mysql8.0/:/var/lib/mysql
        - ./mysql8.0/:/etc/mysql/conf.d
        - ./mysql8.0/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
      ports:
        - "23380:3306"
      networks:
        - private
        - public

    redis:
      image: redis:latest
      volumes:
        - ../web-data/redis/:/data
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      # ports:
      #   - "6379:6379"
      networks:
        - private

    node:
      # image: node:lts-jessie
      image: node:latest
      volumes:
        - ../web-data/node/:/data
      # ports:
      #   - "3000:3000"
      networks:
        - private

    mailhog:
      image: mailhog/mailhog
      # ports:
      #   - "1025:1025"
      #   - "8025:8025"
      networks:
        - private
